# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c9c7c15df0fa5009663e8ac5af9df69871cc0bd3ba2e4186c160cce03773cfa63ba82f1be3fd1bead418d13de502f861c7c1531bae044683777335cc7db4ab

test:
  secret_key_base: e00bebbe75c9a77b39d309e99160ba90ed0f6778ba4c3cf8b3a6b13207e135bea85d9e25841fa1acbbe7855024a4c078756bb6cbe3a13ef90fbf959f6f2f542b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
